server:
  port: 8888

# dubbo的配置项统一方法哦application-dubbo.properties
#dubbo:
#  application:
#    name: annotation-consumer
#  registry:
#    address: zookeeper://47.111.248.53:2183
#  consumer:
#    timeout: 3000